namespace Prohod.WebApi.VisitRequests.Models.GetUserProcessedVisitRequestsPage;

public record GetUserProcessedVisitRequestsPageResponse(IEnumerable<UserProcessedVisitRequestAggregatedDto> VisitRequests);